### ISSUE TITLE
QA: Does this project is still under development?

### ISSUE THREAD

**Issue by Duan-JM** [RadEdje/RadLens2.0#1]
Hi there,

I am a student major in computer science. This interesting project come to me from the most recent google blogs. I wonder if this project is still under development?

**Comment by RadEdje** [comment]
> Hi there,
> 
> I am a student major in computer science. This interesting project come to me from the most recent google blogs. I wonder if this project is still under development?

Hi there, yes I'm currently still working on it but given the recent COVID-19 pandemic I've had to focus more on my work as a doctor/radiologist. Trying to integrate object detection next (waiting for the object detection API to be upgraded and fully compatible w/ tf 2.0 , particularly tf.contrib)... thanks for your interest.

**Comment by Duan-JM** [comment]
wow, great to see this project is still under development. I will go through the code to see what can I do to help this great project.
